use std::fs;
use std::path::Path;

#[cfg(target_os = "windows")]
fn copy_transcribe_dlls() {
    let src_dir = Path::new("target/release");
    let dest_dir = Path::new("resources");

    if !src_dir.exists() {
        println!("cargo:warning=Target release directory not found, skipping DLL copy");
        return;
    }

    // Ensure resources directory exists
    if !dest_dir.exists() {
        fs::create_dir_all(dest_dir).expect("Failed to create resources directory");
    }

    // Copy DLL files from target/release to resources
    // These DLLs are generated by transcribe-cpp crate during build
    let dlls = [
        "ggml.dll",
        "ggml-base.dll",
        "ggml-cpu-alderlake.dll",
        "ggml-cpu-cannonlake.dll",
        "ggml-cpu-cascadelake.dll",
        "ggml-cpu-haswell.dll",
        "ggml-cpu-icelake.dll",
        "ggml-cpu-sandybridge.dll",
        "ggml-cpu-skylakex.dll",
        "ggml-cpu-sse42.dll",
        "ggml-cpu-x64.dll",
        "ggml-vulkan.dll",
        "transcribe.dll",
    ];

    let mut copied = 0;
    for dll in &dlls {
        let src = src_dir.join(dll);
        let dest = dest_dir.join(dll);
        if src.exists() {
            fs::copy(&src, &dest).expect(&format!("Failed to copy {:?}", src));
            copied += 1;
            println!("cargo:warning=Copied: {}", dll);
        }
    }

    if copied > 0 {
        println!("cargo:warning=Copied {} DLL files to resources/", copied);
    } else {
        println!("cargo:warning=No DLLs found in target/release, will be copied by CI or next build");
    }
}

#[cfg(not(target_os = "windows"))]
fn copy_transcribe_dlls() {
    // 在非 Windows 平台上创建占位 DLL 文件，避免 bundle.resources 的 glob pattern 匹配失败
    let dest_dir = Path::new("resources");

    if !dest_dir.exists() {
        fs::create_dir_all(dest_dir).expect("Failed to create resources directory");
    }

    let placeholder = dest_dir.join("placeholder.dll");
    if !placeholder.exists() {
        fs::write(&placeholder, []).expect("Failed to create placeholder DLL");
        println!("cargo:warning=Created placeholder.dll for non-Windows build");
    }
}

fn main() {
    copy_transcribe_dlls();
    tauri_build::build()
}
